export const CMD = {
  SET_STAGE: 'SET_STAGE',
  SET_MORPH: 'SET_MORPH',
  SET_PARTICLES: 'SET_PARTICLES',
  TRIGGER_FRAGMENT: 'TRIGGER_FRAGMENT',
  PERF_EVENT: 'PERF_EVENT',
  TOGGLE_DEBUG: 'TOGGLE_DEBUG',
};
