export const THEATER_CONSTANTS = {
  // Timing
  OPENING_BLACK_DURATION: 2000,
  CURSOR_BLINK_DELAY: 500,
  TERMINAL_TYPE_SPEED: 50,
  SCREEN_FILL_DELAY: 50,
  NARRATIVE_UPDATE_INTERVAL: 100,

  // Interaction
  MORPH_STEP: 0.1,
  SCROLL_MORPH_MULTIPLIER: 2,
  SCROLL_DEBOUNCE_MS: 16, // ~60fps

  // Visual
  MAX_SCREEN_FILL_LINES: 30,
  STAGE_HUD_OPACITY: 0.7,

  // Z-indexes
  Z_OPENING: 9999,
  Z_MEMORY_FRAGMENT: 100,
  Z_STAGE_HUD: 50,
  Z_NARRATIVE: 40,
  Z_DEV_CONTROLS: 100,
};
