#!/bin/bash
# Rollback script generated by Central Clock setup
echo 'Rolling back Central Clock changes...'
cp central_clock_backup_20250706_215239/*.js* .
rm -rf src/core src/hooks/useCentralClock.js
echo 'Rollback complete'
