# .github/workflows/ci.yml

name: MetaCurtis CI/CD Checks # Workflow name

on:
  push:
    branches: [ main, development ] # Trigger on pushes to main & development
  pull_request:
    branches: [ main, development ] # Trigger on PRs targeting main & development
  workflow_dispatch: {} # Allow manual trigger

jobs:
  # Job 1: Linting, Formatting Checks, and Testing
  lint-and-test: # Combined checks for efficiency before build
    name: Lint, Format & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use v4 action

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use v4 action
        with:
          node-version: '20.x' # Use consistent Node version (e.g., 20.x)
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Use ci for clean installs

      - name: Check Formatting (Prettier)
        run: npm run format:check # Run prettier check script

      - name: Run Linter (ESLint)
        # Use stricter command for CI
        run: eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0

      - name: Run Tests (Vitest)
        run: npm run test # Run vitest script

  # Job 2: Build the Project
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint-and-test # Depends on the first job succeeding
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build # Run vite build script

      - name: Upload Production Artifact
        uses: actions/upload-artifact@v4 # Use v4 action
        with:
          name: build-artifact # Artifact name
          path: dist/ # Path to upload

  # Job 3: Run Lighthouse Checks
  lighthouse:
    name: Lighthouse Checks
    runs-on: ubuntu-latest
    needs: build # Depends on build succeeding
    steps:
      # No checkout needed if only using artifact
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # LHCI might need Node
          cache: 'npm' # Cache npm if installing deps needed by preview/lhci script

      # Install necessary dependencies IF preview or lhci script requires them
      # If `npm run preview` and `npm run lighthouse` only rely on deps from `npm ci` run during build,
      # you might skip this install step if node_modules aren't needed runtime for preview/lhci.
      # However, it's safer to include it unless certain it's unnecessary.
      - name: Install dependencies
        run: npm ci

      - name: Download Build Artifact
        uses: actions/download-artifact@v4 # Use v4 action
        with:
          name: build-artifact # Match artifact name from build job
          path: dist/ # Download to dist directory

      # Start preview server in background & wait for it
      - name: Start Preview Server & Wait
        # Using run instead of backgrounding often simpler if wait-on handles it
        run: |
          npm run preview & # Run in background
          npx wait-on http://localhost:4173 -t 60000 # Wait for server (e.g., 60s timeout)

      - name: Run Lighthouse CI
        # Use the script from package.json which should use the dev dependency
        run: npm run lighthouse
        env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }} # Optional: Add if using LHCI GitHub App for status checks