# .github/workflows/ci.yml

name: MetaCurtis CI/CD Checks # Workflow name

on:
  push:
    branches: [ main, development ] # Trigger on pushes to main & development
  pull_request:
    branches: [ main, development ] # Trigger on PRs targeting main & development
  workflow_dispatch: {} # Allow manual trigger

jobs:
  # Job 1: Linting, Formatting Checks, and Testing
  lint-and-test:
    name: Lint, Format & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check Formatting (Prettier)
        run: npm run format:check

      - name: Run Linter (ESLint)
        run: npm run lint # Uses script from package.json - This is fine!

     /* - name: Run Tests (Vitest)
     //   run: npm run test # Includes passWithNoTests via vite.config.js */ 

  # Job 2: Build the Project
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint-and-test # Depends on the first job succeeding
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Upload Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  # Job 3: Run Lighthouse Checks
  lighthouse:
    name: Lighthouse Checks
    runs-on: ubuntu-latest
    needs: build # Depends on build succeeding
    steps:
      # ---vvv THIS STEP WAS MISSING vvv---
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout needed for npm ci below

      # ---^^^ THIS STEP WAS MISSING ^^^---

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies # Now npm ci can find package-lock.json
        run: npm ci

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/

      - name: Start Preview Server & Wait
        run: |
          npm run preview &
          npx wait-on http://localhost:4173 -t 60000

      - name: Run Lighthouse CI
        run: npm run lighthouse
        env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }} # Optional