# .github/workflows/ci.yml

name: MetaCurtis CI/CD Checks # Workflow name

on:
  push:
    branches: [ main, development ] # Trigger on pushes to main & development
  pull_request:
    branches: [ main, development ] # Trigger on PRs targeting main & development
  workflow_dispatch: {} # Allow manual trigger

jobs:
  # Job 1: Linting, Formatting Checks, and Testing
  lint-and-test: # Combined checks for efficiency before build
    name: Lint, Format & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use v4 action

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use v4 action
        with:
          node-version: '20.x' # Use consistent Node version (e.g., 20.x)
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Use ci for clean installs

      - name: Check Formatting (Prettier)
        run: npm run format:check # Run prettier check script

      # ---vvv THE FIX IS HERE vvv---
      - name: Run Linter (ESLint)
        run: npm run lint # Changed from direct eslint call to use npm script
      # ---^^^ THE FIX IS HERE ^^^---

      - name: Run Tests (Vitest)
        run: npm run test # Run vitest script

  # Job 2: Build the Project
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint-and-test # Depends on the first job succeeding
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build # Run vite build script

      - name: Upload Production Artifact
        uses: actions/upload-artifact@v4 # Use v4 action
        with:
          name: build-artifact # Artifact name
          path: dist/ # Path to upload

  # Job 3: Run Lighthouse Checks
  lighthouse:
    name: Lighthouse Checks
    runs-on: ubuntu-latest
    needs: build # Depends on build succeeding
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # LHCI might need Node
          cache: 'npm'

      - name: Install dependencies # Safer to keep for preview/lhci scripts
        run: npm ci

      - name: Download Build Artifact
        uses: actions/download-artifact@v4 # Use v4 action
        with:
          name: build-artifact # Match artifact name from build job
          path: dist/ # Download to dist directory

      - name: Start Preview Server & Wait
        run: |
          npm run preview & # Run in background
          npx wait-on http://localhost:4173 -t 60000 # Wait for server (e.g., 60s timeout)

      - name: Run Lighthouse CI
        run: npm run lighthouse # Use the script from package.json
        env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }} # Optional: Add if using LHCI GitHub App